/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.alg3.agendaMedica;

import projeto.alg3.agendaMedica.convenio.ListaConveniosJFrame;
import projeto.alg3.agendaMedica.medico.ListaMedicosJFrame;
import projeto.alg3.agendaMedica.medico.MedicoJFrame;
import projeto.alg3.agendaMedica.paciente.ListaPacientesJFrame;
import projeto.alg3.agendaMedica.paciente.PacienteJFrame;

/**
 *
 * @author Michel
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitulojLabel = new javax.swing.JLabel();
        TitulojSeparator = new javax.swing.JSeparator();
        cadastra_pacientejButton = new javax.swing.JButton();
        cadastra_medicojButton = new javax.swing.JButton();
        pacientes_cadastradosjButton = new javax.swing.JButton();
        medicos_cadastradosjButton = new javax.swing.JButton();
        agendar_consultajButton = new javax.swing.JButton();
        convenios_cadastradosjButton = new javax.swing.JButton();
        consultas_marcadasjButton = new javax.swing.JButton();
        sairjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitulojLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TitulojLabel.setText("AGENDA MÉDICA");

        cadastra_pacientejButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastra_pacientejButton.setText("Cadastrar Paciente");
        cadastra_pacientejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastra_pacientejButtonActionPerformed(evt);
            }
        });

        cadastra_medicojButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastra_medicojButton.setText("Cadastrar Medico");
        cadastra_medicojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastra_medicojButtonActionPerformed(evt);
            }
        });

        pacientes_cadastradosjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pacientes_cadastradosjButton.setText("Pacientes Cadastrados");
        pacientes_cadastradosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientes_cadastradosjButtonActionPerformed(evt);
            }
        });

        medicos_cadastradosjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        medicos_cadastradosjButton.setText("Medicos Cadastrados");
        medicos_cadastradosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicos_cadastradosjButtonActionPerformed(evt);
            }
        });

        agendar_consultajButton.setBackground(new java.awt.Color(153, 153, 153));
        agendar_consultajButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agendar_consultajButton.setText("Agendar Consulta");

        convenios_cadastradosjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        convenios_cadastradosjButton.setText("Convenios Disponiveis");
        convenios_cadastradosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convenios_cadastradosjButtonActionPerformed(evt);
            }
        });

        consultas_marcadasjButton.setBackground(new java.awt.Color(153, 153, 153));
        consultas_marcadasjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        consultas_marcadasjButton.setText("Consultas Marcadas");

        sairjButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sairjButton.setText("SAIR");
        sairjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultas_marcadasjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TitulojSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cadastra_pacientejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadastra_medicojButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pacientes_cadastradosjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medicos_cadastradosjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agendar_consultajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(convenios_cadastradosjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(TitulojLabel)
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sairjButton)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitulojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitulojSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastra_pacientejButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastra_medicojButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agendar_consultajButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultas_marcadasjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medicos_cadastradosjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convenios_cadastradosjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pacientes_cadastradosjButton)
                .addGap(18, 18, 18)
                .addComponent(sairjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjButtonActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_sairjButtonActionPerformed

    private void cadastra_pacientejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastra_pacientejButtonActionPerformed
        // TODO add your handling code here:
        PacienteJFrame tela = new PacienteJFrame();
        tela.setVisible(true);
    }//GEN-LAST:event_cadastra_pacientejButtonActionPerformed

    private void cadastra_medicojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastra_medicojButtonActionPerformed
        // TODO add your handling code here:
        MedicoJFrame tela = new MedicoJFrame();
        tela.setVisible(true);
    }//GEN-LAST:event_cadastra_medicojButtonActionPerformed

    private void medicos_cadastradosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicos_cadastradosjButtonActionPerformed
        // TODO add your handling code here:
        ListaMedicosJFrame tela = new ListaMedicosJFrame();
        tela.setVisible(true);
    }//GEN-LAST:event_medicos_cadastradosjButtonActionPerformed

    private void convenios_cadastradosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convenios_cadastradosjButtonActionPerformed
        // TODO add your handling code here:
        ListaConveniosJFrame tela = new ListaConveniosJFrame();
        tela.setVisible(true);
    }//GEN-LAST:event_convenios_cadastradosjButtonActionPerformed

    private void pacientes_cadastradosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientes_cadastradosjButtonActionPerformed
        // TODO add your handling code here:
        ListaPacientesJFrame tela = new ListaPacientesJFrame();
        tela.setVisible(true);
    }//GEN-LAST:event_pacientes_cadastradosjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitulojLabel;
    private javax.swing.JSeparator TitulojSeparator;
    private javax.swing.JButton agendar_consultajButton;
    private javax.swing.JButton cadastra_medicojButton;
    private javax.swing.JButton cadastra_pacientejButton;
    private javax.swing.JButton consultas_marcadasjButton;
    private javax.swing.JButton convenios_cadastradosjButton;
    private javax.swing.JButton medicos_cadastradosjButton;
    private javax.swing.JButton pacientes_cadastradosjButton;
    private javax.swing.JButton sairjButton;
    // End of variables declaration//GEN-END:variables
}
