/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.alg3.agendaMedica.medico;

import javax.swing.JOptionPane;

/**
 *
 * @author Michel
 */
public class MedicoEditaJDialog extends javax.swing.JDialog {
    
    private Medico editaMedico;
    private MedicoGerenciaBD bd = new MedicoGerenciaBD();
    /**
     * Creates new form MedicoEditaJDialog
     */
    public MedicoEditaJDialog(java.awt.Frame parent, boolean modal, Medico editar) {
        super(parent, modal);
        initComponents();
        editaMedico = editar;
        nomejTextField.setText(editaMedico.getNome());
        enderecojTextField.setText(editaMedico.getEndereco());
        especialidadejTextField.setText(editaMedico.getEspecialidade());
        conveniojTextField.setText(editaMedico.getConvenio());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulojLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nomejLabel = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        enderecojLabel = new javax.swing.JLabel();
        enderecojTextField = new javax.swing.JTextField();
        especialdadejLabel = new javax.swing.JLabel();
        especialidadejTextField = new javax.swing.JTextField();
        confirmajButton = new javax.swing.JButton();
        cancelajButton = new javax.swing.JButton();
        conveniojLabel = new javax.swing.JLabel();
        conveniojTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titulojLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titulojLabel.setText("                     ATUALIZAÇÃO DE CADASTRO");

        nomejLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nomejLabel.setText("Nome:");

        enderecojLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enderecojLabel.setText("Endereco:");

        especialdadejLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        especialdadejLabel.setText("Especialidade:");

        confirmajButton.setText("Confirma");
        confirmajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmajButtonActionPerformed(evt);
            }
        });

        cancelajButton.setText("Cancelar");
        cancelajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelajButtonActionPerformed(evt);
            }
        });

        conveniojLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        conveniojLabel.setText("Convenio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecojLabel)
                            .addComponent(nomejLabel))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecojTextField)
                            .addComponent(nomejTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especialdadejLabel)
                            .addComponent(conveniojLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especialidadejTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirmajButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelajButton)
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conveniojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejLabel)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecojLabel)
                    .addComponent(enderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especialdadejLabel)
                    .addComponent(especialidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conveniojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conveniojLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmajButton)
                    .addComponent(cancelajButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmajButtonActionPerformed
        // TODO add your handling code here:
        
        editaMedico.setNome(nomejTextField.getText());
        editaMedico.setEndereco(enderecojTextField.getText());
        editaMedico.setEspecialidade(especialidadejTextField.getText());
        editaMedico.setConvenio(conveniojTextField.getText());
        
        if (nomejTextField.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(rootPane,"Verifique se o campo NOME está em branco");
            return;
        }
        
        if (enderecojTextField.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(rootPane,"Verifique se o campo ENDERECO está em branco");
            return;
        }
        if (especialidadejTextField.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(rootPane,"Verifique se o campo ESPECIALIDADE está em branco");
            return;
        }
        if (conveniojTextField.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(rootPane,"Verifique se o campo CONVENIO está em branco");
            return;
        }
        

        bd.setMedico(editaMedico);
        bd.editar();
        
        dispose();
        
    }//GEN-LAST:event_confirmajButtonActionPerformed

    private void cancelajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelajButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelajButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelajButton;
    private javax.swing.JButton confirmajButton;
    private javax.swing.JLabel conveniojLabel;
    private javax.swing.JTextField conveniojTextField;
    private javax.swing.JLabel enderecojLabel;
    private javax.swing.JTextField enderecojTextField;
    private javax.swing.JLabel especialdadejLabel;
    private javax.swing.JTextField especialidadejTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JLabel titulojLabel;
    // End of variables declaration//GEN-END:variables
}
