/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.alg3.agendaMedica.medico;

import javax.swing.JOptionPane;

/**
 *
 * @author Michel
 */
public class MedicoJFrame extends javax.swing.JFrame {
    
    private MedicoGerenciaBD bd = new MedicoGerenciaBD();
    /**
     * Creates new form MedicoJFrame
     */
    public MedicoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulojLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        crmjLabel = new javax.swing.JLabel();
        nomejLabel = new javax.swing.JLabel();
        enderecojLabel = new javax.swing.JLabel();
        especialidadejLabel = new javax.swing.JLabel();
        especialidadejTextField = new javax.swing.JTextField();
        enderecojTextField1 = new javax.swing.JTextField();
        nomejTextField = new javax.swing.JTextField();
        crmjTextField = new javax.swing.JTextField();
        conveniojLabel = new javax.swing.JLabel();
        confirmajButton = new javax.swing.JButton();
        sairjButton = new javax.swing.JButton();
        conveniojTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulojLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titulojLabel.setText("                        CADASTRO DE MEDICOS");

        crmjLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        crmjLabel.setText("CRM:");

        nomejLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nomejLabel.setText("Nome:");

        enderecojLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enderecojLabel.setText("Endereco:");

        especialidadejLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        especialidadejLabel.setText("Especialidade:");

        especialidadejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadejTextFieldActionPerformed(evt);
            }
        });

        nomejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomejTextFieldActionPerformed(evt);
            }
        });

        conveniojLabel.setText("Convênio:");

        confirmajButton.setText("Salvar");
        confirmajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmajButtonActionPerformed(evt);
            }
        });

        sairjButton.setText("Sair");
        sairjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especialidadejLabel)
                            .addComponent(crmjLabel)
                            .addComponent(nomejLabel)
                            .addComponent(enderecojLabel)
                            .addComponent(conveniojLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecojTextField1)
                            .addComponent(nomejTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crmjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(confirmajButton)
                                        .addGap(32, 32, 32)
                                        .addComponent(sairjButton))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(conveniojTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(especialidadejTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crmjLabel)
                    .addComponent(crmjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejLabel)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecojLabel)
                    .addComponent(enderecojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especialidadejLabel)
                    .addComponent(especialidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conveniojLabel)
                    .addComponent(conveniojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmajButton)
                    .addComponent(sairjButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void especialidadejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadejTextFieldActionPerformed

    private void nomejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomejTextFieldActionPerformed

    private void confirmajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmajButtonActionPerformed
        // TODO add your handling code here:
        
        Medico novoMedico = new Medico();
        novoMedico.setCrm(crmjTextField.getText());
        novoMedico.setNome(nomejTextField.getText());
        novoMedico.setEndereco(enderecojTextField1.getText());
        novoMedico.setEspecialidade(especialidadejTextField.getText());
        novoMedico.setConvenio(conveniojTextField.getText());
        
        if (crmjTextField.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(rootPane,"Verifique se o campo CRM está em branco");
            return;
        } 
        if (nomejTextField.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(rootPane,"Verifique se o campo NOME está em branco");
            return;
        } 
        if (enderecojTextField1.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(rootPane,"Verifique se o campo ENDERECO está em branco");
            return;
        } 
        
        if (especialidadejTextField.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(rootPane,"Verifique se o campo ESPECIALIDADE está em branco");
            return;
        } 
        
        if (conveniojTextField.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(rootPane,"Verifique se o campo CONVENIO está em branco");
            return;
        } 

        bd.setMedico(novoMedico);
        bd.inserir();
        
        dispose();
        
    }//GEN-LAST:event_confirmajButtonActionPerformed

    private void sairjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_sairjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicoJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmajButton;
    private javax.swing.JLabel conveniojLabel;
    private javax.swing.JTextField conveniojTextField;
    private javax.swing.JLabel crmjLabel;
    private javax.swing.JTextField crmjTextField;
    private javax.swing.JLabel enderecojLabel;
    private javax.swing.JTextField enderecojTextField1;
    private javax.swing.JLabel especialidadejLabel;
    private javax.swing.JTextField especialidadejTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JButton sairjButton;
    private javax.swing.JLabel titulojLabel;
    // End of variables declaration//GEN-END:variables
}
